# Generated by Django 5.1.4 on 2025-12-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
