# Generated by Django 5.1.4 on 2025-12-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('home_user', '0005_alter_usersession_token_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='authtoken.token', verbose_name='authentication token'),
        ),
    ]
