# Generated by Django 5.1.4 on 2025-12-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0006_alter_usersession_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
