# Generated by Django 5.1.4 on 2025-05-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0005_alter_file_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cdn.tag')),
                ('thumbnail', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdn.file')),
            ],
            bases=('cdn.tag',),
        ),
    ]
