# Generated by Django 5.1.4 on 2025-12-11 03:02

import cdn.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0007_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='key',
            field=models.CharField(default=cdn.models.Share.generate_key, error_messages={'unique': 'key already exists'}, max_length=256, unique=True),
        ),
    ]
