# Generated by Django 5.1.4 on 2025-12-14 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0010_videodetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='cdn.file', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liked_by', 'media')},
        ),
    ]
