# Generated by Django 5.1.4 on 2025-12-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0011_alter_videodetail_video_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='cdn.file'),
        ),
    ]
